export const GET_DOCTOR_PROFILES_REQUEST = 'GET_DOCTOR_PROFILES_REQUEST';
export const GET_DOCTOR_PROFILES_SUCCESS = 'GET_DOCTOR_PROFILES_SUCCESS';
export const GET_DOCTOR_PROFILES_FAILURE = 'GET_DOCTOR_PROFILES_FAILURE';

export const GET_DOCTOR_PROFILE_REQUEST = 'GET_DOCTOR_PROFILE_REQUEST';
export const GET_DOCTOR_PROFILE_SUCCESS = 'GET_DOCTOR_PROFILE_SUCCESS';
export const GET_DOCTOR_PROFILE_FAILURE = 'GET_DOCTOR_PROFILE_FAILURE';

export const GET_DOCTOR_PROFILE_BY_ID_REQUEST = 'GET_DOCTOR_PROFILE_BY_ID_REQUEST';
export const GET_DOCTOR_PROFILE_BY_ID_SUCCESS = 'GET_DOCTOR_PROFILE_BY_ID_SUCCESS';
export const GET_DOCTOR_PROFILE_BY_ID_FAILURE = 'GET_DOCTOR_PROFILE_BY_ID_FAILURE';

export const UPDATE_DOCTOR_PROFILE_REQUEST = 'UPDATE_DOCTOR_PROFILE_REQUEST';
export const UPDATE_DOCTOR_PROFILE_SUCCESS = 'UPDATE_DOCTOR_PROFILE_SUCCESS';
export const UPDATE_DOCTOR_PROFILE_FAILURE = 'UPDATE_DOCTOR_PROFILE_FAILURE';

export const DELETE_DOCTOR_REQUEST = 'DELETE_DOCTOR_REQUEST';
export const DELETE_DOCTOR_SUCCESS = 'DELETE_DOCTOR_SUCCESS';
export const DELETE_DOCTOR_FAILURE = 'DELETE_DOCTOR_FAILURE';
