export const GET_PATIENT_PROFILE_BY_ID_REQUEST = 'GET_PATIENT_PROFILE_BY_ID_REQUEST';
export const GET_PATIENT_PROFILE_BY_ID_SUCCESS = 'GET_PATIENT_PROFILE_BY_ID_SUCCESS';
export const GET_PATIENT_PROFILE_BY_ID_FAILURE = 'GET_PATIENT_PROFILE_BY_ID_FAILURE';

export const GET_PATIENT_PROFILE_REQUEST = 'GET_PATIENT_PROFILE_REQUEST';
export const GET_PATIENT_PROFILE_SUCCESS = 'GET_PATIENT_PROFILE_SUCCESS';
export const GET_PATIENT_PROFILE_FAILURE = 'GET_PATIENT_PROFILE_FAILURE';

export const UPDATE_PATIENT_PROFILE_REQUEST = 'UPDATE_PATIENT_PROFILE_REQUEST';
export const UPDATE_PATIENT_PROFILE_SUCCESS = 'UPDATE_PATIENT_PROFILE_SUCCESS';
export const UPDATE_PATIENT_PROFILE_FAILURE = 'UPDATE_PATIENT_PROFILE_FAILURE';

export const DELETE_PATIENT_REQUEST = 'DELETE_PATIENT_REQUEST';
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS';
export const DELETE_PATIENT_FAILURE = 'DELETE_PATIENT_FAILURE';



