export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';

export const UPDATE_APPOINTMENT_STATUS_REQUEST = 'UPDATE_APPOINTMENT_STATUS_REQUEST';
export const UPDATE_APPOINTMENT_STATUS_SUCCESS = 'UPDATE_APPOINTMENT_STATUS_SUCCESS';
export const UPDATE_APPOINTMENT_STATUS_FAILURE = 'UPDATE_APPOINTMENT_STATUS_FAILURE';

export const RESCHEDULE_APPOINTMENT_REQUEST = 'RESCHEDULE_APPOINTMENT_REQUEST';
export const RESCHEDULE_APPOINTMENT_SUCCESS = 'RESCHEDULE_APPOINTMENT_SUCCESS';
export const RESCHEDULE_APPOINTMENT_FAILURE = 'RESCHEDULE_APPOINTMENT_FAILURE';

export const GET_APPOINTMENTS_BY_DOCTOR_REQUEST = 'GET_APPOINTMENTS_BY_DOCTOR_REQUEST';
export const GET_APPOINTMENTS_BY_DOCTOR_SUCCESS = 'GET_APPOINTMENTS_BY_DOCTOR_SUCCESS';
export const GET_APPOINTMENTS_BY_DOCTOR_FAILURE = 'GET_APPOINTMENTS_BY_DOCTOR_FAILURE';

export const GET_APPOINTMENTS_BY_PATIENT_REQUEST = 'GET_APPOINTMENTS_BY_PATIENT_REQUEST';
export const GET_APPOINTMENTS_BY_PATIENT_SUCCESS = 'GET_APPOINTMENTS_BY_PATIENT_SUCCESS';
export const GET_APPOINTMENTS_BY_PATIENT_FAILURE = 'GET_APPOINTMENTS_BY_PATIENT_FAILURE';

export const DELETE_APPOINTMENT_REQUEST = 'DELETE_APPOINTMENT_REQUEST';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FAILURE = 'DELETE_APPOINTMENT_FAILURE';
